version: "3.9"
services:
    app:
        container_name: trekbag_local
        build: .
        ports:
            - 3000:5000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run dev
        environment:
            - CHOKIDAR_USEPOLLING=true
